"""Render Table 1 (LaTeX) from the CSVs written by ``langsensor.eval.table1``.

    python -m langsensor.paper.table1 \
        --seen artifacts/results/static/table1_seen.csv --seen outputs/table1/table1_seen.csv \
        --unseen artifacts/results/static/table1_unseen.csv --unseen outputs/table1/table1_unseen.csv \
        --out outputs/paper/table1.tex

Several CSVs may be given per split; the newest file wins per row, so fresh
results override archived ones while rows that were not re-run (3D-ViSTA) are
kept from the archive.
"""
from __future__ import annotations

import argparse
import glob as globlib
from pathlib import Path

import pandas as pd


#: Display order.  The three calibration variants are indented under the
#: Scaffolded-LLM row they modify.
ROW_ORDER = [
    ("gt_llm", "Scaffolded-LLM", False),
    ("gt_llm_scale", "+ global rescale", True),
    ("gt_llm_axis_scale", "+ per-axis rescale", True),
    ("gt_llm_incontext", "+ in-context", True),
    ("gt_vlm", "Scaffolded-VLM", False),
    ("vista_gmm", "3D-ViSTA (fine-tuned)", False),
    ("gt_lss", r"\lsm{} (ours)", False),
]

OURS_KEY = "gt_lss"

#: (mean column, std column, how "best" is defined)
METRICS = [
    ("rmse_mean", "rmse_std", "min"),
    ("nll_mean", "nll_std", "min"),
    ("anees", "nees_std", "near3"),
]

ANEES_TARGET = 3.0

#: A row is discarded when its n falls below this fraction of the largest n in
#: the file -- the signature of a run that died partway.
MIN_N_FRACTION = 0.9


def load(patterns: list[str]) -> pd.DataFrame:
    """Merge every matching CSV, newest file winning per approach."""
    paths = sorted({Path(p) for pat in patterns for p in globlib.glob(pat)},
                   key=lambda p: p.stat().st_mtime)
    if not paths:
        raise SystemExit(f"no CSV matched: {patterns}")
    frames = []
    for p in paths:
        frames.append(pd.read_csv(p))
        print(f"  read {p}  ({len(frames[-1])} rows)")
    df = pd.concat(frames, ignore_index=True)
    df = df.drop_duplicates(subset=["approach"], keep="last")

    # A driver treats an API failure as a per-query warning and still writes a
    # row, so a stage that ran out of credit mid-way leaves a plausible-looking
    # line built on a handful of queries (a real one: gt_llm_incontext, n=8 of
    # 400). Those must never reach the table -- drop them loudly.
    if "n" in df.columns and len(df):
        full = int(df["n"].max())
        short = df[df["n"] < MIN_N_FRACTION * full]
        for _, row in short.iterrows():
            print(f"  DROPPED {row['approach']}: n={int(row['n'])} of {full} "
                  f"-- incomplete run, row will print as '--'")
        df = df[df["n"] >= MIN_N_FRACTION * full]
    return df.set_index("approach")


def best_key(df: pd.DataFrame, mean_col: str, how: str, keys: list[str]) -> str | None:
    """Which row wins this column. For ANEES, 'best' is closest to 3, not lowest."""
    avail = [k for k in keys if k in df.index and pd.notna(df.at[k, mean_col])]
    if not avail:
        return None
    if how == "min":
        return min(avail, key=lambda k: float(df.at[k, mean_col]))
    return min(avail, key=lambda k: abs(float(df.at[k, mean_col]) - ANEES_TARGET))


def cell(df: pd.DataFrame, key: str, mean_col: str, std_col: str, winner: bool) -> str:
    if key not in df.index or pd.isna(df.at[key, mean_col]):
        return "--"
    mean, std = float(df.at[key, mean_col]), float(df.at[key, std_col])
    body = f"${mean:.2f} \\pm {std:.2f}$"
    return f"\\cellcolor{{green!25}}{body}" if winner else body


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seen", action="append", required=True,
                    help="CSV path or glob; repeatable, newest wins per approach.")
    ap.add_argument("--unseen", action="append", required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    splits = [("val\\_seen", load(args.seen)), ("val\\_unseen", load(args.unseen))]
    keys = [k for k, _, _ in ROW_ORDER]

    present = {k for _, df in splits for k in df.index if k in set(keys)}
    missing = [k for k in keys if k not in present]
    if missing:
        print(f"WARNING: no data for {missing} -- those rows print as '--'")

    winners = {
        (si, mean_col): best_key(df, mean_col, how, keys)
        for si, (_, df) in enumerate(splits)
        for mean_col, _, how in METRICS
    }

    lines = [
        "% Generated by langsensor.paper.table1 -- do not hand-edit.",
        "\\begin{table}[!htb]",
        "    \\centering",
        "    \\small",
        "    \\caption{Grounding accuracy and calibration on unambiguous utterances",
        "    ($\\text{ambiguity}=1$) with the ground-truth anchor proposer. Best per",
        "    column shaded green; for ANEES, ``best'' is closest to 3.}",
        "    \\label{tab:unambig_grounding}",
        "    \\resizebox{\\textwidth}{!}{%",
        "    \\begin{tabular}{l ccc ccc}",
        "        \\toprule",
        "                       & \\multicolumn{3}{c}{val\\_seen} & \\multicolumn{3}{c}{val\\_unseen} \\\\",
        "        \\cmidrule(lr){2-4} \\cmidrule(lr){5-7}",
        "        Method         & RMSE $\\downarrow$ & NLL $\\downarrow$ & ANEES $\\to 3$",
        "                       & RMSE $\\downarrow$ & NLL $\\downarrow$ & ANEES $\\to 3$ \\\\",
        "        \\midrule",
    ]

    for key, label, indent in ROW_ORDER:
        if key == OURS_KEY:
            lines.append("        \\midrule")
            lines.append("        \\rowcolor{gray!8}")
        name = f"\\quad {label}" if indent else label
        cells = [
            cell(df, key, mean_col, std_col, winners[(si, mean_col)] == key)
            for si, (_, df) in enumerate(splits)
            for mean_col, std_col, _ in METRICS
        ]
        lines.append(f"        {name:<26} & " + " & " .join(cells) + " \\\\")

    n_note = ", ".join(
        f"{name.replace(chr(92)+'_','_')} $n={int(df['n'].max())}$"
        for name, df in splits if "n" in df.columns and len(df)
    )
    lines += [
        "        \\bottomrule",
        "    \\end{tabular}}",
        f"    % {n_note}",
        "\\end{table}",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}  ({n_note})")
    for si, (name, _) in enumerate(splits):
        for mean_col, _, how in METRICS:
            w = winners[(si, mean_col)]
            print(f"  best {name:<12} {mean_col:<10} ({how:<5}) -> {w}")


if __name__ == "__main__":
    main()
